services:
  - type: web
    name: lavanya-tts
    env: python
    plan: standard
    buildCommand: |
      # Install and configure Git LFS
      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
      apt-get install git-lfs
      git lfs install
      
      # Set Git LFS to skip downloading files that fail
      git config lfs.fetchexclude "Fastspeech2_HS/hifigan/denorm/test_243.npy.pt"
      
      # Pull LFS files with continue on error
      git lfs pull || echo "Some LFS files may have failed to download, continuing build..."
      
      # Install Python dependencies
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      
      # Install ESPnet library
      pip install espnet==202304
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300 --keep-alive 120 --max-requests 3 --max-requests-jitter 2 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: WORKERS
        value: "2"
      - key: TIMEOUT
        value: "300"
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/Fastspeech2_HS
      - key: CHUNK_SIZE
        value: "100"
      - key: MAX_TEXT_LENGTH
        value: "2000"
      - key: GUNICORN_CMD_ARGS
        value: "--preload"
      - key: GIT_LFS_SKIP_SMUDGE
        value: "1"
      - key: MODEL_BASE_URL
        value: "https://your-storage-url.com/models"
      - key: LOCAL_MODEL_DIR
        value: "/opt/render/project/src/models_cache"
    disk:
      name: audio
      mountPath: /opt/render/project/src/static/audio
      sizeGB: 2
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    healthCheckPath: /
    healthCheckTimeout: 300