services:
  - type: web
    name: lavanya-tts
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: WORKERS
        value: "1"
      - key: TIMEOUT
        value: "300"
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/Fastspeech2_HS
    disk:
      name: audio
      mountPath: /opt/render/project/src/static/audio
      sizeGB: 1 